"""add tech_stack to companies

Revision ID: 2e8bcf8a5a49
Revises: b67779bb47a3
Create Date: 2026-04-09 14:04:07.142961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8bcf8a5a49'
down_revision: Union[str, Sequence[str], None] = 'b67779bb47a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('tech_stack', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'tech_stack')
    # ### end Alembic commands ###
